name: Swift Test Runner

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-20.04.06
    steps:
    - name: Install Swift
      uses: slashmo/install-swift@v0.1.0
      with:
        version: 5.8
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Tests
      run: swift test
    
